{"name": "test_add_multiple_students", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/tests/DataDriven/TestCases/DataFile.json'", "trace": "def test_add_multiple_students():\n        api_url = \"https://thetestingworldapi.com/api/studentsDetails\"\n        f = open(\n>           \"/tests/DataDriven/TestCases/DataFile.json\")\nE       FileNotFoundError: [Errno 2] No such file or directory: '/tests/DataDriven/TestCases/DataFile.json'\n\nDataDriven\\TestCases\\TestCases.py:11: FileNotFoundError"}, "start": 1659021967002, "stop": 1659021967003, "uuid": "c8a3b7dd-d9af-4353-aadb-31aea1edc1ac", "historyId": "f4ee5d3714603908355a8871f1076731", "testCaseId": "19bac2bc630b53b4d69777f6663155ac", "fullName": "tests.DataDriven.TestCases.TestCases#test_add_multiple_students", "labels": [{"name": "parentSuite", "value": "tests.DataDriven.TestCases"}, {"name": "suite", "value": "TestCases"}, {"name": "host", "value": "131921-T480"}, {"name": "thread", "value": "4812-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.DataDriven.TestCases.TestCases"}]}